# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4e3a94f51e529e4b19d37abc018cdb2006f922094a8ac15832ca0f6be38634fc8560a2e0ae09bcc595532d3bedd96e9c1c6c69e20328c4d379afea35bfde9b2

test:
  secret_key_base: adfa9047af94b842720489d4bb00641c1b123dffa0c0928ed46ae7692162a55a6b1a13b10515490a3553a41b3e077c22d6e8fd7b964ef53d9273a49964d1f017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
